---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boids-simulation
  namespace: boids-simu
  labels:
    app: boids-simulation
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: boids-simulation
  template:
    metadata:
      labels:
        app: boids-simulation
    spec:
      containers:
        - name: boids-simulation
          image: ghcr.io/cyokozai/grafana-nautilus-simu:59f5e60f6c5522bd9fcfaf66defe08326f950b31
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: boids-simulation-config
          resources:
            requests:
              cpu: "10m"
              memory: "32Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
